version: '3.0'

networks:
    test_net:
    product_net:
        ipam:
            config:
                - subnet: 192.168.0.0/24

services:
    football-manager-api:
        image: golang:latest
        container_name: football-manager-api
        environment:
            ## I conveniently sets the data base to the tests one so I reuse the data here.
            # But I'd rather prefer to provide a DSN to an external DB (dev_db), that's why I'm not reusing
            # football-manager-db-test service
            - "DB_DSN=root:${MYSQL_ROOT_PASSWORD}@tcp(football-manager-db)/footballmanager_test?charset=utf8&parseTime=True&loc=Local"
            - 'API_HOSTNAME=0.0.0.0:8081'
            - 'API_LOG_FILE=/var/log/footballmanagerapi/footballmanagerapi.log'
            # GIN API integrates env variable for mode.
            # Values: Release/debug/test.
            # Release will not display error reasons whereas debug/test mode will
            - 'GIN_MODE=release'
            # Authorization passphrase to encrypt/decrypt authorization tokens. hard coded here but must not be in git repo
            - "AUTH_SECRET=${AUTH_SECRET}"
        volumes:
            - ${API_DIR}:${CONTAINER_API_DIR}
        working_dir: ${CONTAINER_API_DIR}
        depends_on:
            - football-manager-db
        networks:
            product_net:
                ipv4_address: 192.168.0.4
        ports:
            - 8081:8081
        expose:
            - 8081

    football-manager-db:
        image: mariadb:latest
        container_name: football-manager-db
        restart: always
        volumes:
            - ${TEST_DATA_DIR}:/docker-entrypoint-initdb.d/
        environment:
            - "MYSQL_ALLOW_EMPTY_PASSWORD=NO"
            - "MYSQL_DATABASE=footballmanager"
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        networks:
            product_net:
                ipv4_address: 192.168.0.6
        ports:
            - 8088:3306
        expose:
            - 3306

    football-manager-api-test:
        image: golang:latest
        container_name: football-manager-api-test
        environment:
            - "DB_DSN=root:${MYSQL_ROOT_PASSWORD}@tcp(football-manager-db-test)/footballmanager_test?charset=utf8&parseTime=True&loc=Local"
            - 'API_LOG_FILE=var/log/footballmanagerapi/footballmanagerapi.log'
            # Authorization passphrase to encrypt/decrypt authorization tokens
            - "AUTH_SECRET=${AUTH_SECRET}"
        volumes:
            - ${API_DIR}:${CONTAINER_API_DIR}
        working_dir: ${CONTAINER_API_DIR}
        depends_on:
            - football-manager-db-test
        networks:
            test_net:

    football-manager-db-test:
        image: mariadb:latest
        container_name: football-manager-db-test
        restart: always
        volumes:
            - ${TEST_DATA_DIR}:/docker-entrypoint-initdb.d/
        environment:
            - 'MYSQL_ALLOW_EMPTY_PASSWORD=NO'
            - 'MYSQL_DATABASE=footballmanager_test'
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        networks:
            test_net:
        ports:
            - 3306:3306
        expose:
            - 3306
